
const KEY='netapi_studio_v1';
const seed={apps:[
{id:1,name:'Network Monitor',clientId:'app_netmon_01',status:'Active',owner:'NOC Team',redirect:'https://example.local/callback',scopes:'devices:read metrics:read alerts:write'},
{id:2,name:'Config Automation',clientId:'app_config_02',status:'Active',owner:'Platform Team',redirect:'https://automation.local/oauth',scopes:'devices:read config:write jobs:write'},
{id:3,name:'Inventory Portal',clientId:'app_inventory_03',status:'Disabled',owner:'IT Team',redirect:'https://inventory.local/auth',scopes:'devices:read inventory:read'}
],apis:[
{id:11,name:'List Devices',method:'GET',path:'/api/v1/devices',group:'Devices',auth:'Bearer Token',status:'Published',description:'Returns network devices with filtering and pagination.'},
{id:12,name:'Create Device',method:'POST',path:'/api/v1/devices',group:'Devices',auth:'OAuth 2.0',status:'Published',description:'Creates a managed network device.'},
{id:13,name:'Get Metrics',method:'GET',path:'/api/v1/devices/:id/metrics',group:'Monitoring',auth:'API Key',status:'Published',description:'Returns CPU, memory, latency and traffic metrics.'},
{id:14,name:'Push Config',method:'POST',path:'/api/v1/devices/:id/config',group:'Automation',auth:'OAuth 2.0',status:'Draft',description:'Queues a configuration deployment job.'}
],keys:[
{id:21,name:'NOC Production',prefix:'nk_live_a82f',status:'Active',scope:'Read/Write',created:'2026-08-10',last:'5 min ago'},
{id:22,name:'Reporting',prefix:'nk_live_c91d',status:'Active',scope:'Read Only',created:'2026-08-18',last:'2 hours ago'}
],webhooks:[
{id:31,name:'Critical Alerts',url:'https://hooks.example.local/network-alerts',event:'alert.created',status:'Active',secret:'whsec_demo'},
{id:32,name:'Device Changes',url:'https://hooks.example.local/device-events',event:'device.updated',status:'Paused',secret:'whsec_demo2'}
],requests:[
{id:41,method:'GET',path:'/api/v1/devices',code:200,latency:82,time:'10:04:21'},
{id:42,method:'GET',path:'/api/v1/devices/1/metrics',code:200,latency:121,time:'10:03:55'},
{id:43,method:'POST',path:'/api/v1/devices/4/config',code:202,latency:244,time:'10:03:14'},
{id:44,method:'GET',path:'/api/v1/devices/404',code:404,latency:45,time:'10:02:41'}
],settings:{baseUrl:'https://api.network.local',rate:1000,version:'v1',docs:true}};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||seed,state={page:'dashboard',search:''};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),save=()=>localStorage.setItem(KEY,JSON.stringify(db));
function toast(m){let x=document.querySelector('.toast');x.textContent=m;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2000)}
function badge(x){let c={Active:'bgreen',Published:'bgreen',Disabled:'bred',Paused:'byellow',Draft:'bgray'}[x]||'bblue';return `<span class="badge ${c}">${esc(x)}</span>`}
function shell(){document.querySelector('#app').innerHTML=`<aside class="side"><div class="brand">NetAPI <span>Studio</span></div><nav class="nav">${[['dashboard','▦ Dashboard'],['apps','▣ Apps'],['apis','⌘ API Endpoints'],['keys','🔑 API Keys'],['webhooks','↗ Webhooks'],['playground','▶ API Playground'],['requests','◷ Request Logs'],['docs','▤ API Docs'],['analytics','▥ Analytics'],['settings','⚙ Settings']].map(([p,l])=>`<button class="${state.page===p?'active':''}" onclick="go('${p}')">${l}</button>`).join('')}</nav></aside><main class="main"><header class="top"><div class="actions"><button class="btn mobile">☰</button><input class="search" placeholder="Search apps & APIs..." value="${esc(state.search)}" oninput="state.search=this.value;render()"></div><div class="actions"><button class="btn" onclick="exportData()">Export</button><button class="btn primary" onclick="quickAdd()">+ Create</button></div></header><section id="page" class="content"></section></main><div id="modal" class="modalbg"><div id="modalBody" class="modal"></div></div><div class="toast"></div>`;renderPage()}
function go(p){state.page=p;state.search='';shell()}function render(){renderPage()}function renderPage(){document.querySelector('#page').innerHTML=({dashboard,apps,apis,keys,webhooks,playground,requests,docs,analytics,settings}[state.page])()}
function stat(a,b,c){return `<div class="card"><div class="label">${a}</div><div class="value">${b}</div><div class="green">${c}</div></div>`}
function dashboard(){return `<div class="head"><div><h1>Networking Apps & APIs</h1><p>Build, secure, test and monitor network integrations</p></div><button class="btn primary" onclick="openApp()">+ New App</button></div><div class="grid stats">${stat('Applications',db.apps.length,'OAuth clients')}${stat('API Endpoints',db.apis.length,'REST resources')}${stat('Active Keys',db.keys.filter(x=>x.status==='Active').length,'Credentials')}${stat('Requests Today','24.8K','+18.4%')}</div><br><div class="grid two"><div class="card"><h3>API Traffic</h3>${[['Devices API',82],['Monitoring API',67],['Automation API',48],['Inventory API',35]].map(([n,v])=>`<p>${n}<span style="float:right">${v}%</span></p><div class="bar"><i style="width:${v}%"></i></div>`).join('')}</div><div class="card"><h3>Platform Health</h3><div class="kv"><span>API Gateway</span>${badge('Active')}</div><div class="kv"><span>OAuth Service</span>${badge('Active')}</div><div class="kv"><span>Webhook Worker</span>${badge('Active')}</div><div class="kv"><span>Docs Portal</span>${badge('Published')}</div></div></div><br><div class="card"><h3>Recent Requests</h3>${requestTable(db.requests.slice(0,5))}</div>`}
function apps(){let a=db.apps.filter(x=>JSON.stringify(x).toLowerCase().includes(state.search.toLowerCase()));return `<div class="head"><div><h1>Applications</h1><p>OAuth clients and networking integrations</p></div><button class="btn primary" onclick="openApp()">+ New App</button></div><div class="grid three">${a.map(x=>`<div class="card"><div class="kv"><strong>${esc(x.name)}</strong>${badge(x.status)}</div><p class="label">Client ID</p><code>${esc(x.clientId)}</code><div class="kv"><span>Owner</span><strong>${esc(x.owner)}</strong></div><div class="kv"><span>Scopes</span><small>${esc(x.scopes)}</small></div><button class="btn" onclick="openApp(${x.id})">Edit</button> <button class="btn danger" onclick="remove('apps',${x.id})">Delete</button></div>`).join('')}</div>`}
function apis(){let a=db.apis.filter(x=>JSON.stringify(x).toLowerCase().includes(state.search.toLowerCase()));return `<div class="head"><div><h1>API Endpoints</h1><p>Create and manage networking REST endpoints</p></div><button class="btn primary" onclick="openApi()">+ Endpoint</button></div><div class="grid">${a.map(x=>`<div class="card endpoint"><div class="kv"><span><b class="method ${x.method}">${x.method}</b> <code style="display:inline;padding:5px">${esc(x.path)}</code></span>${badge(x.status)}</div><h3>${esc(x.name)}</h3><p>${esc(x.description)}</p><div class="kv"><span>Group: ${esc(x.group)}</span><span>Auth: ${esc(x.auth)}</span></div><button class="btn" onclick="openApi(${x.id})">Edit</button> <button class="btn danger" onclick="remove('apis',${x.id})">Delete</button></div>`).join('')}</div>`}
function keys(){return `<div class="head"><div><h1>API Keys</h1><p>Manage credentials used by network applications</p></div><button class="btn primary" onclick="newKey()">+ Generate Key</button></div><div class="card"><table class="table"><thead><tr><th>Name</th><th>Key Prefix</th><th>Scope</th><th>Status</th><th>Created</th><th>Last Used</th><th>Actions</th></tr></thead><tbody>${db.keys.map(k=>`<tr><td>${esc(k.name)}</td><td><code style="display:inline;padding:4px">${esc(k.prefix)}••••</code></td><td>${esc(k.scope)}</td><td>${badge(k.status)}</td><td>${k.created}</td><td>${k.last}</td><td><button class="btn" onclick="toggleKey(${k.id})">${k.status==='Active'?'Disable':'Enable'}</button> <button class="btn danger" onclick="remove('keys',${k.id})">Revoke</button></td></tr>`).join('')}</tbody></table></div>`}
function webhooks(){return `<div class="head"><div><h1>Webhooks</h1><p>Push network events to external applications</p></div><button class="btn primary" onclick="openWebhook()">+ Webhook</button></div><div class="grid two">${db.webhooks.map(w=>`<div class="card"><div class="kv"><strong>${esc(w.name)}</strong>${badge(w.status)}</div><p><b>Event:</b> ${esc(w.event)}</p><code>${esc(w.url)}</code><p><b>Signing secret:</b> ${esc(w.secret.slice(0,8))}••••</p><button class="btn" onclick="openWebhook(${w.id})">Edit</button> <button class="btn" onclick="testWebhook(${w.id})">Test</button> <button class="btn danger" onclick="remove('webhooks',${w.id})">Delete</button></div>`).join('')}</div>`}
function playground(){return `<div class="head"><div><h1>API Playground</h1><p>Try simulated network API requests</p></div></div><div class="grid two"><div class="card"><div class="toolbar"><select id="pgMethod"><option>GET</option><option>POST</option><option>PUT</option><option>DELETE</option></select><input id="pgPath" style="flex:1" value="/api/v1/devices"></div><label>Request body</label><textarea id="pgBody" class="code" style="width:100%;min-height:170px">{"name":"Branch-Router-02","ip":"10.20.0.1"}</textarea><br><button class="btn primary" onclick="runRequest()">Send Request</button></div><div class="card"><h3>Response</h3><pre id="pgResponse" class="code">Ready.</pre></div></div>`}
function requests(){return `<div class="head"><div><h1>Request Logs</h1><p>Inspect API traffic, response codes and latency</p></div><button class="btn danger" onclick="clearRequests()">Clear</button></div><div class="card">${requestTable(db.requests.filter(x=>JSON.stringify(x).toLowerCase().includes(state.search.toLowerCase())))}</div>`}
function requestTable(a){return `<div class="table-wrap"><table class="table"><thead><tr><th>Method</th><th>Path</th><th>Status</th><th>Latency</th><th>Time</th></tr></thead><tbody>${a.map(r=>`<tr><td><b class="${r.method}">${r.method}</b></td><td>${esc(r.path)}</td><td>${r.code}</td><td>${r.latency} ms</td><td>${r.time}</td></tr>`).join('')}</tbody></table></div>`}
function docs(){return `<div class="head"><div><h1>API Documentation</h1><p>Interactive reference for your networking platform</p></div></div><div class="grid two"><div class="card"><h3>Quick Start</h3><p>Base URL</p><code>${esc(db.settings.baseUrl)}/api/${esc(db.settings.version)}</code><p>Authentication header</p><code>Authorization: Bearer YOUR_TOKEN</code><h3>Example</h3><code>GET /api/v1/devices
Accept: application/json</code></div><div class="card"><h3>Available Resources</h3>${db.apis.map(a=>`<div class="kv"><span><b class="${a.method}">${a.method}</b> ${esc(a.path)}</span><span>${esc(a.group)}</span></div>`).join('')}</div></div>`}
function analytics(){return `<div class="head"><div><h1>API Analytics</h1><p>Usage, latency and reliability</p></div></div><div class="grid stats">${stat('Success Rate','99.72%','Healthy')}${stat('P95 Latency','184 ms','-12 ms')}${stat('Rate Limited','127','Today')}${stat('Webhook Success','98.9%','Last 24h')}</div><br><div class="grid two"><div class="card"><h3>Response Codes</h3>${[['2xx',91],['4xx',7],['5xx',2]].map(([n,v])=>`<p>${n}<span style="float:right">${v}%</span></p><div class="bar"><i style="width:${v}%"></i></div>`).join('')}</div><div class="card"><h3>Top Consumers</h3>${db.apps.map((a,i)=>`<div class="kv"><span>${esc(a.name)}</span><strong>${[12.4,8.7,3.1][i]||1.2}K</strong></div>`).join('')}</div></div>`}
function settings(){return `<div class="head"><div><h1>API Settings</h1><p>Gateway and developer platform configuration</p></div><button class="btn primary" onclick="saveSettings()">Save</button></div><div class="card"><div class="form"><div class="field"><label>Base URL</label><input id="sBase" value="${esc(db.settings.baseUrl)}"></div><div class="field"><label>Default Version</label><input id="sVer" value="${esc(db.settings.version)}"></div><div class="field"><label>Rate Limit / minute</label><input id="sRate" type="number" value="${db.settings.rate}"></div><div class="field"><label>Public Docs</label><select id="sDocs"><option value="true">Enabled</option><option value="false">Disabled</option></select></div></div></div>`}
function modal(h){document.querySelector('#modalBody').innerHTML=h;document.querySelector('#modal').classList.add('show')}function closeModal(){document.querySelector('#modal').classList.remove('show')}function f(id,l,v,t='text'){return `<div class="field"><label>${l}</label><input id="${id}" type="${t}" value="${esc(v)}"></div>`}function sel(id,l,o,v){return `<div class="field"><label>${l}</label><select id="${id}">${o.map(x=>`<option ${x===v?'selected':''}>${x}</option>`).join('')}</select></div>`}function v(id){return document.getElementById(id).value}
function openApp(id=0){let a=id?db.apps.find(x=>x.id===id):{name:'',clientId:'app_'+Math.random().toString(36).slice(2,10),status:'Active',owner:'',redirect:'',scopes:'devices:read'};modal(`<h2>${id?'Edit':'New'} Application</h2><div class="form">${f('an','Name',a.name)}${f('ac','Client ID',a.clientId)}${sel('as','Status',['Active','Disabled'],a.status)}${f('ao','Owner',a.owner)}${f('ar','Redirect URL',a.redirect)}${f('asc','Scopes',a.scopes)}</div><div class="foot"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveApp(${id})">Save</button></div>`)}
function saveApp(id){let o={name:v('an'),clientId:v('ac'),status:v('as'),owner:v('ao'),redirect:v('ar'),scopes:v('asc')};if(id)Object.assign(db.apps.find(x=>x.id===id),o);else db.apps.push({id:Date.now(),...o});save();closeModal();renderPage();toast('Application saved')}
function openApi(id=0){let a=id?db.apis.find(x=>x.id===id):{name:'',method:'GET',path:'/api/v1/',group:'Devices',auth:'Bearer Token',status:'Draft',description:''};modal(`<h2>${id?'Edit':'New'} API Endpoint</h2><div class="form">${f('en','Name',a.name)}${sel('em','Method',['GET','POST','PUT','DELETE'],a.method)}${f('ep','Path',a.path)}${f('eg','Group',a.group)}${sel('ea','Authentication',['Bearer Token','OAuth 2.0','API Key','None'],a.auth)}${sel('es','Status',['Draft','Published'],a.status)}<div class="field full"><label>Description</label><textarea id="ed">${esc(a.description)}</textarea></div></div><div class="foot"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveApi(${id})">Save</button></div>`)}
function saveApi(id){let o={name:v('en'),method:v('em'),path:v('ep'),group:v('eg'),auth:v('ea'),status:v('es'),description:v('ed')};if(id)Object.assign(db.apis.find(x=>x.id===id),o);else db.apis.push({id:Date.now(),...o});save();closeModal();renderPage();toast('Endpoint saved')}
function openWebhook(id=0){let w=id?db.webhooks.find(x=>x.id===id):{name:'',url:'',event:'alert.created',status:'Active',secret:'whsec_'+Math.random().toString(36).slice(2)};modal(`<h2>${id?'Edit':'New'} Webhook</h2><div class="form">${f('wn','Name',w.name)}${f('wu','URL',w.url)}${sel('we','Event',['alert.created','device.updated','device.offline','config.completed'],w.event)}${sel('ws','Status',['Active','Paused'],w.status)}${f('wsec','Signing Secret',w.secret)}</div><div class="foot"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveWebhook(${id})">Save</button></div>`)}
function saveWebhook(id){let o={name:v('wn'),url:v('wu'),event:v('we'),status:v('ws'),secret:v('wsec')};if(id)Object.assign(db.webhooks.find(x=>x.id===id),o);else db.webhooks.push({id:Date.now(),...o});save();closeModal();renderPage();toast('Webhook saved')}
function remove(t,id){if(confirm('Delete this item?')){db[t]=db[t].filter(x=>x.id!==id);save();renderPage();toast('Deleted')}}function newKey(){let name=prompt('API key name:','New Integration');if(!name)return;db.keys.push({id:Date.now(),name,prefix:'nk_live_'+Math.random().toString(36).slice(2,6),status:'Active',scope:'Read/Write',created:new Date().toISOString().slice(0,10),last:'Never'});save();renderPage();toast('API key generated')}function toggleKey(id){let k=db.keys.find(x=>x.id===id);k.status=k.status==='Active'?'Disabled':'Active';save();renderPage()}function testWebhook(){toast('Test webhook delivered: HTTP 200')}function clearRequests(){if(confirm('Clear request logs?')){db.requests=[];save();renderPage()}}
function runRequest(){let method=v('pgMethod'),path=v('pgPath'),lat=50+Math.floor(Math.random()*180),code=method==='POST'?201:200;db.requests.unshift({id:Date.now(),method,path,code,latency:lat,time:new Date().toLocaleTimeString()});save();document.querySelector('#pgResponse').textContent=JSON.stringify({status:'success',method,path,requestId:'req_'+Math.random().toString(36).slice(2),data:{message:'Simulated networking API response'}},null,2);toast('Request completed')}
function exportData(){let b=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='netapi-studio-export.json';a.click();URL.revokeObjectURL(a.href)}function quickAdd(){state.page==='apis'?openApi():state.page==='webhooks'?openWebhook():state.page==='keys'?newKey():openApp()}function saveSettings(){db.settings.baseUrl=v('sBase');db.settings.version=v('sVer');db.settings.rate=+v('sRate')||1000;db.settings.docs=v('sDocs')==='true';save();toast('Settings saved')}document.addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});shell();
